CREATE TABLE IF NOT EXISTS sync_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    clan_id BIGINT UNSIGNED NOT NULL,
    discord_guild_id VARCHAR(32) NOT NULL,
    initiated_by_discord_user_id VARCHAR(32) NULL,
    initiated_by_name VARCHAR(255) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'running',
    started_at_utc DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    finished_at_utc DATETIME(3) NULL,
    total_members INT NOT NULL DEFAULT 0,
    changed_members INT NOT NULL DEFAULT 0,
    skipped_members INT NOT NULL DEFAULT 0,
    blocked_members INT NOT NULL DEFAULT 0,
    error_members INT NOT NULL DEFAULT 0,
    summary_text TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_sync_runs_clan_id (clan_id),
    KEY idx_sync_runs_discord_guild_id (discord_guild_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sync_run_members (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    sync_run_id BIGINT UNSIGNED NOT NULL,
    discord_user_id VARCHAR(32) NOT NULL,
    discord_username VARCHAR(255) NULL,
    discord_display_name VARCHAR(255) NULL,
    resolved_rsn VARCHAR(255) NULL,
    resolved_rank_name VARCHAR(100) NULL,
    resolved_by VARCHAR(100) NULL,
    status VARCHAR(50) NOT NULL,
    added_role_ids_csv TEXT NULL,
    removed_role_ids_csv TEXT NULL,
    blocked_role_ids_csv TEXT NULL,
    guest_dm_attempted TINYINT(1) NOT NULL DEFAULT 0,
    guest_dm_success TINYINT(1) NOT NULL DEFAULT 0,
    guest_dm_error TEXT NULL,
    notes TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_sync_run_members_sync_run_id (sync_run_id),
    KEY idx_sync_run_members_discord_user_id (discord_user_id),
    CONSTRAINT fk_sync_run_members_sync_run FOREIGN KEY (sync_run_id) REFERENCES sync_runs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
