CREATE TABLE IF NOT EXISTS app_settings (
    setting_key VARCHAR(190) NOT NULL PRIMARY KEY,
    setting_value LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS installs (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    installed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    app_version VARCHAR(50) NOT NULL,
    installed_by_ip VARCHAR(45) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
